### ISSUE TITLE
resizer高度有问题

### ISSUE THREAD

**Issue by xinnai** [heqing0712/vue-codepen#3]
1、resizer向上拖动时候高度出现问题
2、切换视图之后resizer高度出现问题
![Snip20210301_2](https://user-images.githubusercontent.com/23135336/109445598-e5817f00-7a7a-11eb-9500-d2389524bafc.png)
![Snip20210301_1](https://user-images.githubusercontent.com/23135336/109445609-e9ad9c80-7a7a-11eb-8650-0859f8cf05e7.png)

**Comment by heqing0712** [comment]
该代码很久没更新了，该开源是我当初刚刚学习vue的一个项目，从jquery转为vue的，谢谢你的关注和反馈
